openapi: 3.0.3
info:
  title: WebShop API
  version: 1.0.0

tags:
  - name: Goods
    description: Управление товарами

paths:
  /addgood:
    post:
      tags:
        - Goods
      summary: Добавить товар

components:
  schemas:
    Good:
