server:
  port: 8080

s3:
  accessKeyId: KM2S7GR01BUER3FKDN0U
  secretAccessKey: MXG3weJGL25Uk3RLkktsZNt1AXwG7pI6tiq7FMnR
  minioUrl: https://s3.twcstorage.ru
  region: ru-1
  bucket: 242358d3-goods-bucket
logging:
  level:
    org.springdoc: DEBUG
    org.springframework: WARN
    ru.webshop: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  cache:
    disabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    cookie:
      same-site: none
      secure: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: backend
  public-urls:
    - '/api/products/**'
    - '/v3/api-docs.yaml'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/api/auth/**'
    - '/api/password/**'
    - '/api/token/**'
    - '/api/activate-account'
    - '/v3/api-docs/**'
    - '/swagger-ui.html'
    - '/swagger-ui/**'
    - '/swagger-resources/**'
    - '/webjars/**'
    - '/v2/api-docs'
    - '/v2/api-docs/**'
    - '/webjars/swagger-ui/**'
    - '/v3/api-docs'
    - '/swagger-ui/index.html'
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/goods_db
    url: jdbc:postgresql://goods_db/goods_db
    username: postgres
    password: postgres
  security:
    jwt:
      secret-key: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
      expiration: 360000
      refresh-expiration: 604800
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

telegram:
  bot:
    token: 7543101157:AAESvq4Mu3IHx-2gtkj4xJwktoohT9RbWqE
