server:
  port: 8080

s3:
  accessKeyId: KFzkrASGUVF0CPAYBI1u
  secretAccessKey: gYkGKXl1r5b4TuJVc4kDMTitg63fT64aRfDWlnsI
  minioUrl: http://localhost:9000
  region: us-east-1
  bucket: goods

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    cookie:
      same-site: none
      secure: true
  application:
    name: backend
  public-urls:
    - "/api/**" # для тестирования
    - "/api/auth/**"
    - "/api/password/**"
    - "/api/token/**"
    - "/api/activate-account"
    - "/v3/api-docs/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    - "/webjars/**"
    - "/v2/api-docs"
    - "/v2/api-docs/**"
    - "/webjars/swagger-ui/**"
    - "/v3/api-docs"
    - "/swagger-ui/index.html"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/goods_db
    #url: jdbc:postgresql://goods_db/goods_db
    username: postgres
    password: postgres
  security:
    jwt:
      secret-key: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
      expiration: 3600
      refresh-expiration: 604800
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

telegram:
  bot:
    token: 7543101157:AAESvq4Mu3IHx-2gtkj4xJwktoohT9RbWqE